- name: variables
  hosts: local
  connection: local
  vars: # PLAY level variables, global variables
    COURSE: "DevOps with AWS"
    DURATION: 120HRS
    TRAINER: Sivakumar
  tasks:
  - name: print the variables
    vars:
      COURSE: Ansible #task level variables,accessible only with in the task. Task variables can override play level variables. it is also called as local variables
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"  

  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"  
