- name: variables
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: please enter the course name
  - name: DURATION
    prompt: please enter the Duration
  - name: TRAINER
    prompt: please enter the trainer name  
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"  
