- name: DevOps course information
  hosts: local
  connection: local
  vars: #map
    course_name: "DevOps with AWS" #string
    Duration: 120HRS #number
    Topics: # list , - means list, when we print in terminal [] this means list.
    - linux
    - shell
    - ansible
    - AWS
    live: true #boolean (means true or false)
    tools: #map, when we print in terminal {} this means map
      ci: jenkins
      cloud: AWS
      containerisation: docker
    tasks:
    - name: print the course information
      ansible.builtin.debug:
        msg: "Hello I am learning {{ course_name }}, Duration: {{ Duration }}, Topics are {{ topics }}, is it live?: {{ live }}, tools covered are {{ tools }}"