- name: print the facts
  hosts: web
  tasks:
  - name: print the facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}" # ansible_facts is a reserved keyword of ansible to get complete information of nodes